version: "3.3"

services:
  app:
    container_name: blackbird-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/blackbird
      - spring.datasource.username=crescer
      - spring.datasource.password=crescer
      - spring.jpa.hibernate_ddl-auto=validate
    networks:
      - app

  db:
    image: postgres:14.7-alpine
    container_name: db
    environment:
      - POSTGRES_USER=crescer
      - POSTGRES_PASSWORD=crescer
      - POSTGRES_DB=blackbird
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - app

volumes:
  postgres-data:

networks:
  app:
